### ISSUE TITLE
non-tito builds don't contain %{dist} and %{foremandis} macros in SRPM name

### ISSUE THREAD

**Issue by evgeni** [theforeman/obal#318]
https://github.com/theforeman/foreman-packaging/pull/8364 (3.3 tito-based build) links in checks to "koji/rubygem-foreman_webhooks-3.0.4-1.fm3_3.el8.src.rpm"
https://github.com/theforeman/foreman-packaging/pull/8362 (nightly, non-tito) links to "koji/rubygem-foreman_webhooks-3.0.4-1.src.rpm"

This is confusing :)

**Comment by ehelms** [comment]
The design idea with build SRPM is that it only needs to build the SRPM once and then send that up to Koji or mock. There are two approaches we can take:

 1) Change it so that it generates an SRPM per dist and foremandist
 2) Change our task info logic to look at child tasks and pluck out hte value form the rebuildSRPM task

**Comment by evgeni** [comment]
I think 2 is the cleaner solution given the (now explained and found good) design :)

**Comment by evgeni** [comment]
@ehelms another interesting side-effect: nightly builds don't have their nightly tag when built from a PR: http://koji.katello.org/koji/buildinfo?buildID=72915

(cc @ekohl )

**Comment by ehelms** [comment]
@evgeni This was created back when we used Koji and was primarily a CI issue where the individual jobs per dist were not clear, now with Copr we display it as:

```
@theforeman-bot
copr/foreman_ygg_worker-opensuse-leap-15.5-x86_64 — Copr build
[Details](https://copr.fedorainfracloud.org/coprs/build/8162168)
@theforeman-bot
copr/foreman_ygg_worker-rhel-7-x86_64 — Copr build
[Details](https://copr.fedorainfracloud.org/coprs/build/8162167)
@theforeman-bot
copr/foreman_ygg_worker-rhel-8-x86_64 — Copr build
[Details](https://copr.fedorainfracloud.org/coprs/build/8162166)
@theforeman-bot
copr/foreman_ygg_worker-rhel-9-x86_64 — Copr build
```

Where the chroot is used for each one from Copr. This would not include the foremandist aspect however. The builds as listed (https://copr.fedorainfracloud.org/coprs/g/theforeman/plugins-nightly-staging/builds/) lack the dist and foremandist because that represents the SRPM that was uploaded. If you think we should still tackle this and ensure it includes dist/foremandist in the SRPM then I'll tackle making this change:

> Change it so that it generates an SRPM per dist and foremandist

**Comment by evgeni** [comment]
I think the display with Copr is sufficiently distinct now, so I'd close this as "not needed anymore".
